plugins {
    id "com.android.application"
}

android {
    namespace "dev.squarednetizen.guicontrolsgallery"
    compileSdk 34
    buildToolsVersion providers.gradleProperty(
        "sdlBuildToolsVersion"
    ).getOrElse("34.0.0")

    defaultConfig {
        applicationId "dev.squarednetizen.guicontrolsgallery"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "0.1.0"
        buildConfigField "boolean",
            "MANAGE_ALL_FILES_ON_FIRST_START",
            "false"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["src/main/jniLibs"]
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
